root = "."
testdata_dir = "testdata"
tmp_dir = "air-build"

[build]
  args_bin = []
  bin = "/air-build/main.exe"
  cmd = "go build -o /air-build/main.exe ./app/main.go"
  poll = true
  poll_interval = 500
  delay = 1000
  exclude_dir = ["assets", "air-build", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["internal", "app"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
